inniin/urls.py
from django.urls import re_path, include, path
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView, LogoutView

from roomrentals.views import HomeView
from roomrentalscn.views import ChineseHomeView

urlpatterns = [
	path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', HomeView.as_view(), name='ENG_home'),
    path('cn/', ChineseHomeView.as_view(), name='CHI_home'),
    path('roomrentals/', include('roomrentals.urls', namespace='roomrentals')),
    path('roomrentalscn/', include('roomrentalscn.urls', namespace='roomrentalscn')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('aboutcn/', TemplateView.as_view(template_name='aboutcn.html'), name='aboutcn'),
    path('contact/',  TemplateView.as_view(template_name='contact.html'), name='contact'),
    path('contactcn/',  TemplateView.as_view(template_name='contactcn.html'), name='contactcn'),
]

roomrentals/urls.py
from django.urls import re_path

from .views import (
    DayView,
    )

app_name = 'roomrentals'

urlpatterns = [
    re_path(r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/$',DayView.as_view(), name='archive_day'),
    #url(r'^create/$', RoomRentalCreateView.as_view(), name='create'),
    #url(r'^(?P<pk>\d+)/edit/$', RoomRentalUpdateView.as_view(), name='edit'),
    #url(r'^(?P<pk>\d+)/$', RoomRentalUpdateView.as_view(), name='detail'),
	
	# dollarsign '$' is end of string
]

templates/about.html
{% extends "base.html" %}
{% block head_title %}About || {{ block.super }}{% endblock head_title %}

{% block content %}

	<div class="span8" id="divMain">

    <h1>Find Your Next Stay</h1>
   
    <hr>
    <div class="row">
        <div class="col-lg-4">

        			<h4 style="color:#373737;">Need Viewing Updates?</h4>

        			<hr>

	<p style="color:#373737;" align="left">
		Submit your leasing requirements on the form on the right. inniin personnal will update you daily via Whatsapp on the upcoming viewings!
	</p>

    <p align="center">
		Require Additional Assistance?
	</p>

	<p style="color:#373737;" align="left">
		You may wish to contact us via our live chat which is available from 9am to 5pm SGT, Monday through Friday.
	</p>
	

	<p><a style="color:#FFF" class="btn btn-secondary" href="#" role="button">Live Chat</a></p>


      <hr>

        </div>
        <div class="col-lg-8">
        	<h4 style="color:#373737;">Subscribe To Daily Updates</h4>
        	<hr>
        	
        	<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfSv_61GBT4dPeAPtRmuPWmPuqaJzENgGLQ-sqS11kMcUB9oA/viewform?embedded=true" width="450" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

        	<hr>

        </div>
      </div>
    
    
	</div>
	
{% endblock content %}

templates/aboutcn.html
{% extends "basecn.html" %}
{% block head_title %}我要租房 || {{ block.super }}{% endblock head_title %}

{% block content %}

			<div class="span8" id="divMain">
	
    
	<h1>我要租房</h1>
	<hr>

    <div class="row">
        <div class="col-lg-4">

        <h4 style="color:#373737;">我要订阅迎迎推送通知服务!</h4>

       	<hr>

	<p style="color:#373737;" align="left">
		您想要在第一时间被通知迎迎平台上对您有兴趣的房租广告吗? 请填写表格，迎迎介绍组将会用微信联系您！
	</p>

    <p align="center">
		还有疑问?
	</p>

	<p style="color:#373737;" align="left">
		您能向我们的迎迎客服询问。迎迎客服时段：9:00 上午 - 5:00 下午，周一至周五。
	</p>
	

	<p><a style="color:#FFF" class="btn btn-secondary" href="#" role="button">网上客服</a></p>


      <hr>

        </div>
        <div class="col-lg-8">
        	<h4 style="color:#373737;">Submit Property Details</h4>
        	<hr>
        	
        	<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfSv_61GBT4dPeAPtRmuPWmPuqaJzENgGLQ-sqS11kMcUB9oA/viewform?embedded=true" width="450" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

        	<hr>

        </div>
      </div>

	</div>
	
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
	
	<head> 
	
	{% include 'snippets/css.html' %}

	</head>


	<body>
  
	<title>{% block head_title %}inniin{% endblock head_title %}</title>

	
	
	<div class='container'>
	

		{% include 'snippets/nav.html' %}
		
		{% block content %}{% endblock content %}

    </div>

		{% include 'snippets/js.html' %}
		{% include 'snippets/jq.html' %}

	</body>

</html>

templates/basecn.html
<!DOCTYPE html>
<html lang="en">
	
	<head> 
	
	{% include 'snippets/css.html' %}

	</head>


	<body>
  
	<title>{% block head_title %}迎迎{% endblock head_title %}</title>

	
	
	<div class='container'>
	

		{% include 'snippets/navcn.html' %}
		
		{% block content %}{% endblock content %}

    </div>

		{% include 'snippets/js.html' %}
		{% include 'snippets/jq.html' %}

	</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% block head_title %}Contact || {{ block.super }}{% endblock head_title %}

{% block content %}

	<div class="span8" id="divMain">
	
    
	<h1>Post Your Property</h1>
	<hr>

    <div class="row">
        <div class="col-lg-4">

        <h4 style="color:#373737;">Lease Your Property!</h4>

       	<hr>

	<p style="color:#373737;" align="left">
		You have a property and wish to lease it out? Fill in the form on the right and inniin personnal will connect with you shortly!
	</p>

    <p align="center">
		Require Additional Assistance?
	</p>

	<p style="color:#373737;" align="left">
		You may wish to contact us via our live chat which is available from 9am to 5pm SGT, Monday through Friday.
	</p>
	

	<p><a style="color:#FFF" class="btn btn-secondary" href="#" role="button">Live Chat</a></p>


      <hr>

        </div>
        <div class="col-lg-8">
        	<h4 style="color:#373737;">Submit Property Details</h4>
        	<hr>
        	
        	<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfSv_61GBT4dPeAPtRmuPWmPuqaJzENgGLQ-sqS11kMcUB9oA/viewform?embedded=true" width="450" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

        	<hr>

        </div>
      </div>

	</div>
	
{% endblock content %}

templates/contactcn.html
{% extends "basecn.html" %}
{% block head_title %}出租房间 || {{ block.super }}{% endblock head_title %}

{% block content %}

		<div class="span8" id="divMain">
	
    
	<h1>出租房间</h1>
	<hr>

    <div class="row">
        <div class="col-lg-4">

        <h4 style="color:#373737;">我要出租房间!</h4>

       	<hr>

	<p style="color:#373737;" align="left">
		您有房子想出租吗? 请填写表格，迎迎介绍组将会用微信联系您！
	</p>

    <p align="center">
		还有疑问?
	</p>

	<p style="color:#373737;" align="left">
		您能向我们的迎迎客服询问。迎迎客服时段：9:00 上午 - 5:00 下午，周一至周五。
	</p>
	

	<p><a style="color:#FFF" class="btn btn-secondary" href="#" role="button">网上客服</a></p>


      <hr>

        </div>
        <div class="col-lg-8">
        	<h4 style="color:#373737;">Submit Property Details</h4>
        	<hr>
        	
        	<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfSv_61GBT4dPeAPtRmuPWmPuqaJzENgGLQ-sqS11kMcUB9oA/viewform?embedded=true" width="450" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

        	<hr>

        </div>
      </div>

	</div>
	
{% endblock content %}

templates/form.html
{% extends "base.html" %}

{% block head_title %} {{ title }} || {{ block.super }}{% endblock head_title %}

{% block content %}

<h1> {{ title }} </h1>

{% include 'snippets/form-snippet.html' %}

{% endblock %}

templates/home.html
{% extends "base.html" %}


{% block content %}
	<div class='row'>
	<div class='col-sm-12 text-center col-sm-offset-3'>
	
	
	<h3><a href='{% url "roomrentals:archive_day" year=yyear month=ymonth day=yday %}'>previous day hometemplate</a>
	<h1> {{ today }} </h1>
	<h3><a href='{% url "roomrentals:archive_day" year=tyear month=tmonth day=tday %}'>next day</a>	
	
	{% for obj in object_list %}



	

		<div class="card card-inverse" style="background-color: #333; border-color: #333;">
			
			<h4>{{ obj.appointmenttime }}</h4>
			<p>{{ obj.itemdesc }}</p>
			<p>{{ obj.itemnote }}</p>
		
		<ul>
			{% for item in obj.item_set.all %}
			<li style='margin-bottom: 15px'>{{ obj.itemdesc }}</li>
				{% for others in obj.get_itemdesc %}
					<a href='{{ request.path }}?q= {{others}}'>{{ others }}</a>
				{% endfor %}
			{% endfor %}
		</ul>
		</div>
		<p>
		</p>
{% endfor %}

	</div>
	</div>

{% endblock %}

templates/homecn.html
{% extends "basecn.html" %}


{% block content %}
	<div class='row'>
	<div class='col-sm-12 text-center col-sm-offset-3'>
	
	
	<h3><a href='{% url "roomrentalscn:archive_day" year=yyear month=ymonth day=yday %}'>previous day hometemplate</a>
	<h1> {{ day|date:"n月 j日 | Y年" }}  </h1>
	<h3><a href='{% url "roomrentalscn:archive_day" year=tyear month=tmonth day=tday %}'>next day</a>	
	
	{% for obj in object_list %}



	

		<div class="card card-inverse" style="background-color: #333; border-color: #333;">
			
			<h4>{{ obj.appointmenttime }}</h4>
			<p>{{ obj.itemdesc }}</p>
			<p>{{ obj.itemnote }}</p>
		
		<ul>
			{% for item in obj.item_set.all %}
			<li style='margin-bottom: 15px'>{{ obj.itemdesc }}</li>
				{% for others in obj.get_itemdesc %}
					<a href='{{ request.path }}?q= {{others}}'>{{ others }}</a>
				{% endfor %}
			{% endfor %}
		</ul>
		</div>
		<p>
		</p>
{% endfor %}

	</div>
	</div>

{% endblock %}

templates/index.html
  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Cover</h3>
              <nav class="nav nav-masthead">
                <a class="nav-link active" href="#">Home</a>
                <a class="nav-link" href="#">Features</a>
                <a class="nav-link" href="#">Contact</a>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Cover your page.</h1>
            <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
            <p class="lead">
              <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Cover template for <a href="https://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>
    </body>

templates/upload.html
{% extends "base.html" %}
{% block content %}
<div class='row'>
    <div class='col-6 offset-3'>
        <div class='item-loading-queue'>

        </div>
        <form class='cfeproj-upload-form'>
            <input class='cfeproj-upload-file form-control' type='file' accept='audio/*,video/*,image/*' multiple='multiple' />
        </form>
    </div>
</div>
{% endblock content %}